steps:
  # Build the application image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/korebaps-app/korebaps-app', '.']
  
  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/$PROJECT_ID/korebaps-app/korebaps-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'korebaps-app'
      - '--image=us-east4-docker.pkg.dev/$PROJECT_ID/korebaps-app/korebaps-app'
      - '--region=us-east4'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--set-secrets'
      - 'DB_HOST=db-host:latest'
      - 'DB_PORT=db-port:latest'
      - 'DB_NAME=db-name:latest'
      - 'DB_USER=db-user:latest'
      - 'DB_PASSWORD=db-password:latest'
      - 'ADMIN_PASSWORD=admin-password:latest'
      - '--set-env-vars'
      - 'DB_SSL=true'
      - 'DB_SSL_CA=ca.pem'
      - 'DB_SSL_REJECT_UNAUTHORIZED=true'
      - 'REACT_APP_API_BASE_URL=https://korebaps-app-335189014297.us-east4.run.app'

images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/korebaps-app/korebaps-app'
